"""empty message

Revision ID: 06db3bd3cb07
Revises: 67eb4e468c7f
Create Date: 2021-05-13 10:57:15.622117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06db3bd3cb07'
down_revision = '67eb4e468c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'added')
    # ### end Alembic commands ###
