"""empty message

Revision ID: 5b055e133fda
Revises: 1c249b6b7390
Create Date: 2021-05-12 15:30:10.097055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b055e133fda'
down_revision = '1c249b6b7390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('poster', sa.String(length=100), nullable=True),
    sa.Column('postnote', sa.String(length=100000), nullable=True),
    sa.Column('pictures', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('compare_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('pictures', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('added', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    # ### end Alembic commands ###
